import { Ionicons, MaterialIcons } from "@expo/vector-icons";
import * as Print from "expo-print";
import { useLocalSearchParams, useNavigation } from "expo-router";
import * as Sharing from "expo-sharing";
import React, { useEffect, useState } from "react";
import {
    ActivityIndicator,
    Alert,
    Dimensions,
    ScrollView,
    StyleSheet,
    Text,
    TouchableOpacity,
    View,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import apiClient from "../../hooks/apiClient";

const { width } = Dimensions.get("window");

export default function EventAIReport() {
    const navigation = useNavigation();
    const { eventId } = useLocalSearchParams();

    const [loading, setLoading] = useState(true);
    const [reportData, setReportData] = useState(null);

    useEffect(() => {
        navigation.setOptions({ headerShown: false });
        generateReport();
    }, []);

    const generateReport = async () => {
        try {
            setLoading(true);
            // Increase timeout specifically for this heavy AI call
            const response = await apiClient.post(
                `/reports/events/${eventId}/ai-report`,
                {},
                { timeout: 60000 }
            );

            if (response.data.success) {
                setReportData(response.data.data);
            } else {
                Alert.alert("Error", "Failed to generate report.");
            }
        } catch (error) {
            console.error("Report Generation Error:", error);
            Alert.alert("Error", "Could not connect to AI service.");
        } finally {
            setLoading(false);
        }
    };

    // 👇 NEW FUNCTION: Generates PDF from the AI data
    const handleDownloadPdf = async () => {
        if (!reportData) return;

        try {
            const { narrative, metrics } = reportData;

            // Convert markdown bold (**text**) to HTML bold (<b>text</b>)
            const formattedNarrative = narrative
                .replace(/\*\*(.*?)\*\*/g, '<b>$1</b>')
                .replace(/\n/g, '<br />');

            const htmlContent = `
        <html>
          <head>
            <style>
              body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #333; }
              .header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #0077B6; padding-bottom: 20px; }
              h1 { color: #0077B6; margin: 0; font-size: 24px; }
              .subtitle { color: #666; font-size: 14px; margin-top: 5px; }
              
              .section { margin-bottom: 30px; background: #f9f9f9; padding: 20px; border-radius: 8px; }
              h2 { color: #191823; font-size: 18px; margin-top: 0; border-bottom: 1px solid #ddd; padding-bottom: 10px; }
              
              .metrics-grid { display: flex; flex-wrap: wrap; gap: 20px; margin-top: 15px; }
              .metric-box { flex: 1; min-width: 45%; background: #fff; padding: 15px; border: 1px solid #eee; border-radius: 5px; }
              .metric-val { font-size: 20px; font-weight: bold; color: #0077B6; }
              .metric-lbl { font-size: 12px; color: #666; text-transform: uppercase; letter-spacing: 1px; }

              .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #999; border-top: 1px solid #eee; padding-top: 20px; }
            </style>
          </head>
          <body>
            <div class="header">
              <h1>Event Intelligence Report</h1>
              <div class="subtitle">Generated by Smart Events AI • ${new Date().toLocaleDateString()}</div>
            </div>

            <div class="section">
              <h2>Executive Analysis</h2>
              <div style="line-height: 1.6; font-size: 14px;">
                ${formattedNarrative}
              </div>
            </div>

            <div class="section">
              <h2>Operational Metrics</h2>
              <div class="metrics-grid">
                <div class="metric-box">
                  <div class="metric-val">${metrics.total_attendance}</div>
                  <div class="metric-lbl">Total Attendance</div>
                </div>
                <div class="metric-box">
                  <div class="metric-val">${metrics.total_registrations}</div>
                  <div class="metric-lbl">Total Registrations</div>
                </div>
                <div class="metric-box">
                  <div class="metric-val" style="color: ${parseFloat(metrics.attrition_rate) > 20 ? '#c0392b' : '#2e8b57'}">
                    ${metrics.attrition_rate}
                  </div>
                  <div class="metric-lbl">Attrition Rate</div>
                </div>
                <div class="metric-box">
                  <div class="metric-val">${metrics.avg_latency_minutes} min</div>
                  <div class="metric-lbl">Avg Check-in Wait</div>
                </div>
                 <div class="metric-box">
                  <div class="metric-val">${metrics.peak_entry_window}</div>
                  <div class="metric-lbl">Peak Entry Time</div>
                </div>
              </div>
            </div>

            <div class="footer">
              Confidential Report • Internal Use Only
            </div>
          </body>
        </html>
      `;

            const { uri } = await Print.printToFileAsync({ html: htmlContent });
            await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });

        } catch (error) {
            console.error("PDF Export Error:", error);
            Alert.alert("Error", "Failed to generate PDF file.");
        }
    };

    const renderMetricCard = (icon, label, value, subLabel, color = "#0077B6") => (
        <View style={styles.metricCard}>
            <View style={[styles.iconContainer, { backgroundColor: `${color}15` }]}>
                <Ionicons name={icon} size={24} color={color} />
            </View>
            <Text style={styles.metricValue}>{value}</Text>
            <Text style={styles.metricLabel}>{label}</Text>
            {subLabel && <Text style={styles.metricSubLabel}>{subLabel}</Text>}
        </View>
    );

    if (loading) {
        return (
            <SafeAreaView style={styles.loadingContainer}>
                <ActivityIndicator size="large" color="#0077B6" />
                <Text style={styles.loadingText}>Gemini is analyzing event data...</Text>
                <Text style={styles.loadingSubText}>Calculating attrition, latency & peaks</Text>
            </SafeAreaView>
        );
    }

    if (!reportData) {
        return (
            <SafeAreaView style={styles.container}>
                <Text style={{ padding: 20, textAlign: 'center' }}>No data available. Please try again.</Text>
                <TouchableOpacity onPress={generateReport} style={{ alignSelf: 'center', padding: 10 }}>
                    <Text style={{ color: '#0077B6' }}>Retry</Text>
                </TouchableOpacity>
            </SafeAreaView>
        );
    }

    const { metrics, narrative } = reportData;
    const attritionVal = parseFloat(metrics.attrition_rate);
    const attritionColor = attritionVal > 20 ? "#c0392b" : "#2e8b57";

    return (
        <SafeAreaView style={styles.container}>
            <ScrollView contentContainerStyle={styles.scrollContent}>

                <View style={styles.headerRow}>
                    <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backButton}>
                        <Ionicons name="arrow-back" size={24} color="#333" />
                    </TouchableOpacity>
                    <Text style={styles.headerTitle}>AI Post-Event Analysis</Text>
                    <View style={{ width: 24 }} />
                </View>

                <View style={styles.narrativeCard}>
                    <View style={styles.narrativeHeader}>
                        <MaterialIcons name="auto-awesome" size={24} color="#0077B6" />
                        <Text style={styles.narrativeTitle}>Executive Summary</Text>
                    </View>
                    <Text style={styles.narrativeText}>
                        {narrative}
                    </Text>
                </View>

                <Text style={styles.sectionTitle}>Key Performance Metrics</Text>

                <View style={styles.gridContainer}>
                    {renderMetricCard(
                        "people",
                        "Total Attendance",
                        metrics.total_attendance,
                        `vs ${metrics.total_registrations} Registrations`
                    )}

                    {renderMetricCard(
                        "trending-down",
                        "Attrition Rate",
                        metrics.attrition_rate,
                        attritionVal > 20 ? "High Turnover" : "Healthy Range",
                        attritionColor
                    )}

                    {renderMetricCard(
                        "timer-outline",
                        "Avg Entry Latency",
                        `${metrics.avg_latency_minutes} min`,
                        "Wait time / Delay"
                    )}

                    {renderMetricCard(
                        "time",
                        "Peak Entry",
                        metrics.peak_entry_window,
                        "Busiest hour"
                    )}
                </View>

                {/* Updated Button with handleDownloadPdf */}
                <TouchableOpacity style={styles.exportButton} onPress={handleDownloadPdf}>
                    <Ionicons name="download-outline" size={20} color="#fff" />
                    <Text style={styles.exportButtonText}>Download Full PDF Report</Text>
                </TouchableOpacity>

            </ScrollView>
        </SafeAreaView>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f8f9fa",
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: "#f8f9fa",
    },
    loadingText: {
        marginTop: 20,
        fontSize: 18,
        fontWeight: "600",
        color: "#0077B6",
    },
    loadingSubText: {
        marginTop: 8,
        fontSize: 14,
        color: "#888",
    },
    scrollContent: {
        padding: 20,
    },
    headerRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 20,
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: "700",
        color: "#191823",
    },
    backButton: {
        padding: 8,
        borderRadius: 8,
        backgroundColor: "#fff",
        elevation: 2,
    },
    narrativeCard: {
        backgroundColor: "#fff",
        borderRadius: 16,
        padding: 20,
        marginBottom: 25,
        elevation: 3,
        shadowColor: "#000",
        shadowOpacity: 0.1,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
        borderLeftWidth: 4,
        borderLeftColor: "#0077B6",
    },
    narrativeHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 12,
        gap: 10,
    },
    narrativeTitle: {
        fontSize: 18,
        fontWeight: "700",
        color: "#0077B6",
    },
    narrativeText: {
        fontSize: 15,
        lineHeight: 24,
        color: "#444",
        textAlign: "justify",
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: "700",
        color: "#191823",
        marginBottom: 15,
    },
    gridContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
    },
    metricCard: {
        width: (width - 50) / 2,
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 15,
        marginBottom: 15,
        elevation: 2,
        alignItems: "flex-start",
    },
    iconContainer: {
        padding: 8,
        borderRadius: 8,
        marginBottom: 10,
    },
    metricValue: {
        fontSize: 22,
        fontWeight: "800",
        color: "#191823",
        marginBottom: 2,
    },
    metricLabel: {
        fontSize: 14,
        fontWeight: "600",
        color: "#666",
    },
    metricSubLabel: {
        fontSize: 11,
        color: "#999",
        marginTop: 4,
    },
    exportButton: {
        flexDirection: "row",
        backgroundColor: "#191823",
        paddingVertical: 16,
        borderRadius: 12,
        justifyContent: "center",
        alignItems: "center",
        marginTop: 10,
        gap: 10,
        marginBottom: 30, // Add space at bottom
    },
    exportButtonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "600",
    },
});